name: Issue Hello World

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Job
        run: |
          echo "Running job"
          # Simulate a successful or failing command
          # Use `exit 1` to simulate failure
          exit 0

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"✅ Job is successful! 🎉"}' \
              $SLACK_WEBHOOK_URL
          else
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"❌ Job failed with an error message!"}' \
              $SLACK_WEBHOOK_URL

      - name: Print Final Message
        run: echo "hello this is my first pipeline"
