name: Pull Request Events

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Request Message
        run: echo "This is a pull request event"

