name: Daily Hydration Reminder to Team

on:
  schedule:
    - cron: '* * * * *'  # Every day at 10:00 AM UTC

jobs:
  hydration-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Send Hydration Reminder to Team
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.STAY_HYDRATED }}
        run: |
          USERS="@john @jane @alex"  # Replace with actual Slack usernames
          MESSAGE="$USERS 💧 Time for a Water Break!\n\
Could you please take a sip of water? Your body might be getting dehydrated. Stay hydrated to keep your energy up and your focus sharp — let’s work seamlessly and stay refreshed! 💪"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" \
            "$SLACK_WEBHOOK_URL"
